databases:
  - name: citizennode-db
    databaseName: citizennode
    user: citizen_admin
    plan: free

services:
  - type: web
    name: citizennode-web
    env: node
    plan: free
    rootDir: egov-backend
    buildCommand: npm install --include=dev && npm rebuild && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: "22"
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: citizennode-db
          property: connectionString
      - key: CORS_ORIGINS
        value: "*"
